version: '3.8'

services:
    node:
        build:
            context: ./node
            dockerfile: Dockerfile
        container_name: node
        entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
        command: node index.js
        restart: always
        networks:
            - node-network
        volumes:
            - ./node:/usr/src/app
        tty: true
        depends_on:
            - db

    db:
        build:
            context: ./mysql
            dockerfile: Dockerfile

        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        environment:
            MYSQL_DATABASE: nodedb
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./mysql/data:/var/lib/mysql
        networks:
            - node-network

    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        container_name: nginx
        restart: always
        networks:
            - node-network
        ports:
            - "8080:80"
        depends_on:
            - node
            - db

networks:
    node-network:
        driver: bridge